#!/bin/bash

### BEGIN INIT INFO
# Provides:		test
# Required-Start:	$network $local_fs
# Required-Stop:	$network $local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Start daemon at boot time
# Description:		Enable service provided by daemon
### END INIT INFO

start(){
ifconfig eth0 0;
service networking stop && service networking start;

ip addr add 192.168.1.21/24 broadcast 192.168.1.255 dev br-eth0;
ip link set br-eth0 up promisc on;
ip link add proxy-br-eth1 type veth peer name eth1-br-proxy;
ip link add proxy-br-ex type veth peer name ex-br-proxy;
ip link set eth1-br-proxy up promisc on;
ip link set proxy-br-eth1 up promisc on;
ip link set ex-br-proxy up promisc on;
ip link set proxy-br-ex up promisc on;
ip addr add 192.168.2.21/24 broadcast 192.168.2.255 dev br-eth1;
ip link set br-eth1 up promisc on;
ip link set br-ex up promisc on;

route add default gw 192.168.1.1;
sleep 5;
service openvswitch-switch restart;
ervice ntp restart;
service neutron-dhcp-agent restart
service neutron-l3-agent restart
service neutron-metadata-agent restart
service neutron-plugin-openvswitch-agent restart

echo "*****************************Virtual IP set*****************************"

}
stop(){
}

case "$1" in
start)
start
;;
stop)
stop
;;

*)

echo $"Usage: $0 {start|stop}"
RETVAL=1
esac
exit 0

