#!/bin/bash

### BEGIN INIT INFO
# Provides:		Initial Configurations after fresh installation
# Required-Start:	$local_fs $syslog
# Required-Stop:	$local_fs $syslog
# Default-Start:	3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Start daemon at boot time
# Description:		Enable service provided by daemon
### END INIT INFO

start(){

/bin/sh /CompInstSt.sh;
sync;
sleep 10;

echo "################################################################################################"
echo "*****************************Execution of Compute1 Script Completed*****************************"
echo "################################################################################################"
}
stop(){
rm /etc/rc3.d/S02Comp1
rm /etc/rc4.d/S02Comp1
rm /etc/rc5.d/S02Comp1
rm /etc/rc0.d/K02Comp1
rm /etc/rc1.d/K02Comp1
rm /etc/rc6.d/K02Comp1
}

case "$1" in
start)
start
;;
stop)
stop
;;

*)

echo $"Usage: $0 {start|stop}"
RETVAL=1
esac
exit 0
